// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzOcEtN_gV-MExpwfY6j1QlvvQm5HsWI',
    appId: '1:323486256950:web:4a3d8a42950311431ead97',
    messagingSenderId: '323486256950',
    projectId: 'video-app-f41e3',
    authDomain: 'video-app-f41e3.firebaseapp.com',
    storageBucket: 'video-app-f41e3.appspot.com',
    measurementId: 'G-MCC0ECQVNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRpoQl1nda8naycoYZm5RUmSMRwXm9QWg',
    appId: '1:323486256950:android:b270a7525a330ee81ead97',
    messagingSenderId: '323486256950',
    projectId: 'video-app-f41e3',
    storageBucket: 'video-app-f41e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOO23IaiTJMK5UlKk-h1wrlS0mc1MGB0',
    appId: '1:323486256950:ios:298a73a0e94e16b81ead97',
    messagingSenderId: '323486256950',
    projectId: 'video-app-f41e3',
    storageBucket: 'video-app-f41e3.appspot.com',
    iosBundleId: 'com.example.videoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOO23IaiTJMK5UlKk-h1wrlS0mc1MGB0',
    appId: '1:323486256950:ios:298a73a0e94e16b81ead97',
    messagingSenderId: '323486256950',
    projectId: 'video-app-f41e3',
    storageBucket: 'video-app-f41e3.appspot.com',
    iosBundleId: 'com.example.videoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzOcEtN_gV-MExpwfY6j1QlvvQm5HsWI',
    appId: '1:323486256950:web:360c2a44f2d180841ead97',
    messagingSenderId: '323486256950',
    projectId: 'video-app-f41e3',
    authDomain: 'video-app-f41e3.firebaseapp.com',
    storageBucket: 'video-app-f41e3.appspot.com',
    measurementId: 'G-MJ4TDNB62Y',
  );

}